ccflags-y += -D__CHECK_ENDIAN__ -DDEBUG

obj-$(CONFIG_INTEL_MEI_DAL) += mei_dal.o
mei_dal-objs := dal_class.o
mei_dal-objs += dal_cdev.o
mei_dal-objs += dal_kdi.o
mei_dal-objs += admin_pack_ext.o
mei_dal-objs += admin_pack_int.o
mei_dal-objs += bhp_impl.o
mei_dal-objs += bhp_impl_ta.o
